// The numeric half of the plugin: everything around the ONNX graph.
//
// Deliberately free of OFX and of ONNX Runtime, so it can be tested against the
// Python implementation without a host. tests/cpp/test_pipeline.cpp does that,
// comparing against reference data generated by tools/dump_pipeline_reference.py.
//
// The correspondence that matters:
//     stereo_warp_onnx.py  _aa_weights / _apply_axis  -> resizeDepth
//     stereo_warp_onnx.py  _make_input_tensor         -> buildInputTensor
//     stereo_warp.py       get_mapper                 -> Mapper
//     iw3_ext/depth_file.py  model_depth_size         -> autoDepthSize

#pragma once

#include "numeric_math.h"

#include <cstddef>
#include <cstdint>
#include <utility>
#include <vector>

namespace iw3
{

enum class MapperType
{
    Multiply,
    Shift
};

// The order is the order of the Output parameter's options, and adding to the
// middle would silently change what an already-saved comp means. New modes go
// on the end even when that reads oddly in the menu.
enum class OutputMode
{
    Anaglyph,
    LeftEye,
    RightEye,
    HalfSbs,
    DepthDebug
};

// Which pipeline runs. The first two are the same backward warp with a
// different network; the third is a different pipeline entirely -- forward warp
// into holes, then an inpaint network to fill them.
//
// Same rule as OutputMode: the order is the order of the Model parameter's
// options, and inserting into the middle would silently change what an
// already-saved comp means.
enum class Method
{
    RowFlowV2,
    RowFlowV3,
    MonoBwInpaint,
    // The same pipeline with the temporal inpaint model. The image one has no
    // temporal path at all, so each frame's fill is invented independently and
    // the filled regions crawl; this one mixes along a twelve-frame axis.
    MonoBwInpaintVideo,
    // A third pipeline: a 0.233M-parameter network that emits two sampling
    // deltas, a softmax weight for each, and the hole mask. The eye is the
    // weighted sum of two backward warps rather than one, which is how it
    // represents a pixel that could plausibly come from two places. Its holes
    // are predicted rather than computed, and its fill is the same
    // LightInpaintV1 monobw uses.
    MlbwInpaint
};

struct Settings
{
    double divergence = 2.0;
    double convergence = 0.5;
    bool preserveScreenBorder = false;
    bool depthInverted = false;
    double foregroundScale = 0.0;
    MapperType mapperType = MapperType::Multiply;
    int stereoWidth = 0;  // 0 = auto
    bool undoVideoRange = false;
    OutputMode output = OutputMode::Anaglyph;
    Method method = Method::RowFlowV2;
    size_t model = 0;  // index into the runtime's graphs
    // monobw_inpaint only: how far to grow the hole mask before filling.
    // Counted against the depth's width, so they mean the same thing at any
    // output resolution.
    int maskInnerDilation = 0;
    int maskOuterDilation = 0;
    // Cap the width the inpaint network runs at, 0 for the frame's own. Its
    // memory scales with area, so this is the lever for a smaller card; the
    // fill is composited back at full resolution either way.
    int inpaintMaxWidth = 0;
};

// iw3's depth mappers, for relative depth only.
//
// Exposed through foreground scale rather than by name, because iw3's own help
// says "directly using this option is not recommended, use --foreground-scale
// instead". A fractional scale interpolates two neighbouring mappers, which is
// what resolve_mapper_name() does.
class Mapper
{
public:
    Mapper() = default;
    Mapper(double foregroundScale, MapperType type);

    double operator()(double x) const;
    bool isIdentity() const { return _identity; }

    // The resolved form, small enough to hand to a CUDA kernel by value.
    iw3::math::MapperParams params() const;

private:
    int _a = 3;  // index into the mapper list, 3 == "none"
    int _b = 3;
    double _weight = 0.0;
    MapperType _type = MapperType::Multiply;
    bool _identity = true;
};

// The shape a depth model would have produced for a frame this size.
//
// Resolve hands the plugin depth at composition resolution unconditionally,
// which is the exact case that makes the warp stripe, so this is not optional.
// The rule is from iw3_ext/depth_file.py, itself from
// depth_anything_model.batch_preprocess().
std::pair<int, int> autoDepthSize(int frameWidth, int frameHeight);

// The target size for the depth, honouring an explicit stereo width or falling
// back to autoDepthSize(). Returns {width, height}.
std::pair<int, int> depthTargetSize(int frameWidth, int frameHeight, int stereoWidth);

// One axis of a separable resample: for each output sample, where its taps
// start and what they weigh.
struct ResampleAxis
{
    int inSize = 0;
    int outSize = 0;
    std::vector<int> start;
    std::vector<int> count;
    std::vector<int> offset;     // into weights
    std::vector<float> weights;  // packed, count[i] entries per output
};

// PyTorch's antialiased bilinear resample weights for one axis.
//
// ONNX Resize cannot reproduce this -- see docs/phase2-onnx.md. Public because
// the CUDA path uploads exactly these weights rather than deriving its own,
// which is what keeps the two paths identical.
void buildResampleAxis(ResampleAxis& axis, int inSize, int outSize);

// The CPU resampler. Weights are rebuilt only when a size changes, which is
// once per timeline in practice.
class DepthResizer
{
public:
    void resize(const float* source, int sourceWidth, int sourceHeight,
                std::vector<float>& target, int targetWidth, int targetHeight);

private:
    ResampleAxis _horizontal;
    ResampleAxis _vertical;
    std::vector<float> _scratch;
};

// The model's input: disparity, divergence feature, convergence feature.
// `depth` is already mapped and resized. Writes 3 * width * height floats.
void buildInputTensor(const float* depth, int width, int height,
                      double divergence, double convergence,
                      bool preserveScreenBorder,
                      std::vector<float>& out);

// delta_scale, from the *depth's* width, not the image's.
float deltaScale(int depthWidth);

// Red/cyan Dubois. Each row of the matrix sums to 1.0 across all six
// coefficients, so a grey pair stays grey; that is the property the test checks.
void duboisAnaglyph(const float* left, const float* right, size_t pixels, float* out);

// --- monobw ------------------------------------------------------------------
//
// The forward-warp-and-fill pipeline's first half, from iw3's sbs.monobw. The
// arithmetic is in monobw_math.h and shared with the CUDA kernels; this is the
// CPU driver around it, and the one tests/cpp/test_pipeline.cpp can run.
//
//     stereo_inpaint.py  MonoBW.compute_backward_grid -> monobwGrid
//     stereo_inpaint.py  MonoBW.forward               -> monobwForward

// The sampling grid at the *depth's* resolution.
//
// `gridX` comes back as depthWidth * depthHeight. `gridY` is only depthHeight
// long: it is the same linear ramp in every column, and bilinear interpolation
// of a row-constant plane along x returns that value exactly, so carrying the
// full plane would be a large buffer holding one number per row.
//
// `imageWidth` is the colour frame's, not the depth's -- preserve_screen_border
// derives its ramp from the frame and then scales it back down.
void monobwGrid(const float* depth, int depthWidth, int depthHeight,
                double divergence, double convergence,
                bool preserveScreenBorder, int imageWidth,
                std::vector<float>& gridX, std::vector<float>& gridY);

// The whole of MonoBW.forward: warped eye and hole mask, both at the frame's
// resolution. `image` is three planes of width * height.
//
// `fixScreenBorderMask` is iw3's: 0 leaves the mask alone, 1 clears the
// uninpaintable side, 2 clears both. It only applies when preserve_screen_border
// is off, because with the parallax tapered there is no border stretch to
// suppress. The image model uses 1.
//
// `mask` comes back as 0.0/1.0 floats rather than bytes so it can go straight
// into the morphology, which is arithmetic on floats.
void monobwForward(const float* image, int width, int height,
                   const float* depth, int depthWidth, int depthHeight,
                   double divergence, double convergence,
                   bool preserveScreenBorder, int fixScreenBorderMask,
                   std::vector<float>& eye, std::vector<float>& mask);

// preprocess_mask: threshold, mask_closing, then the two directional dilations.
//
// This is the step between the warp and the inpaint graph, and it is outside
// the graph because the dilation counts are plugin parameters -- the same rule
// that keeps preserve_screen_border out of the warp's graph.
//
// `baseWidth` is the depth's width, which is what iw3 quotes the dilations
// against so a setting means the same thing at any output resolution. Pass 0 to
// take the counts literally.
void maskPreprocess(const float* mask, int width, int height,
                    int innerDilation, int outerDilation, int baseWidth,
                    std::vector<float>& out);

// --- mlbw_l2_inpaint ---------------------------------------------------------
//
// The half of mask_mlbw_l2 that is not the network. Arithmetic in mlbw_math.h,
// shared with the CUDA kernels; these are the CPU drivers around it, and the
// ones tests/cpp/test_pipeline.cpp can run.
//
//     stereo_warp.py     _warp_one_view_mlbw (after the model) -> mlbwWarp
//     stereo_inpaint.py  _postprocess_hole_mask                -> mlbwMask
//
// Both take the network's outputs as arguments rather than running it, because
// in the plugin the network is an ORT call and these are what surround it.

// The two backward warps and the softmax blend, for one eye.
//
// `delta` and `layerWeight` are the model's, each two planes at the depth's
// resolution. `eye` comes back as width * height * 3, in the same orientation
// as `image` -- this does no mirroring, because which eye is being built is the
// caller's business and getting a flip wrong here would be invisible.
//
// The weights are resized to the frame with the *antialiased* resampler, the
// deltas are not. That asymmetry is iw3's; see mlbw_math.h.
void mlbwWarp(const float* image, int width, int height,
              const float* delta, const float* layerWeight,
              int depthWidth, int depthHeight,
              std::vector<float>& eye);

// postprocess_hole_mask: closing on the logits, upscale, threshold, dilate.
//
// `logits` is the mask head's output at the depth's resolution and is *not* a
// mask yet -- it has not been through a sigmoid. The dilation counts are quoted
// against the logits' width, which is what iw3 reads them off.
void mlbwMask(const float* logits, int depthWidth, int depthHeight,
              int width, int height, int innerDilation, int outerDilation,
              std::vector<float>& out);

}  // namespace iw3
