// The numeric half of the plugin: everything around the ONNX graph.
//
// Deliberately free of OFX and of ONNX Runtime, so it can be tested against the
// Python implementation without a host. tests/cpp/test_pipeline.cpp does that,
// comparing against reference data generated by tools/dump_pipeline_reference.py.
//
// The correspondence that matters:
//     stereo_warp_onnx.py  _aa_weights / _apply_axis  -> resizeDepth
//     stereo_warp_onnx.py  _make_input_tensor         -> buildInputTensor
//     stereo_warp.py       get_mapper                 -> Mapper
//     iw3_ext/depth_file.py  model_depth_size         -> autoDepthSize

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace iw3
{

enum class MapperType
{
    Multiply,
    Shift
};

enum class OutputMode
{
    Anaglyph,
    LeftEye,
    RightEye,
    HalfSbs,
    DepthDebug
};

struct Settings
{
    double divergence = 2.0;
    double convergence = 0.5;
    bool preserveScreenBorder = false;
    bool depthInverted = false;
    double foregroundScale = 0.0;
    MapperType mapperType = MapperType::Multiply;
    int stereoWidth = 0;  // 0 = auto
    bool undoVideoRange = false;
    OutputMode output = OutputMode::Anaglyph;
};

// iw3's depth mappers, for relative depth only.
//
// Exposed through foreground scale rather than by name, because iw3's own help
// says "directly using this option is not recommended, use --foreground-scale
// instead". A fractional scale interpolates two neighbouring mappers, which is
// what resolve_mapper_name() does.
class Mapper
{
public:
    Mapper() = default;
    Mapper(double foregroundScale, MapperType type);

    double operator()(double x) const;
    bool isIdentity() const { return _identity; }

private:
    int _a = 3;  // index into the mapper list, 3 == "none"
    int _b = 3;
    double _weight = 0.0;
    MapperType _type = MapperType::Multiply;
    bool _identity = true;
};

// The shape a depth model would have produced for a frame this size.
//
// Resolve hands the plugin depth at composition resolution unconditionally,
// which is the exact case that makes the warp stripe, so this is not optional.
// The rule is from iw3_ext/depth_file.py, itself from
// depth_anything_model.batch_preprocess().
std::pair<int, int> autoDepthSize(int frameWidth, int frameHeight);

// The target size for the depth, honouring an explicit stereo width or falling
// back to autoDepthSize(). Returns {width, height}.
std::pair<int, int> depthTargetSize(int frameWidth, int frameHeight, int stereoWidth);

// PyTorch's antialiased bilinear resample, separable, single channel.
//
// ONNX Resize cannot reproduce this -- see docs/phase2-onnx.md. Weights are
// rebuilt only when a size changes, which is once per timeline in practice.
class DepthResizer
{
public:
    void resize(const float* source, int sourceWidth, int sourceHeight,
                std::vector<float>& target, int targetWidth, int targetHeight);

private:
    struct Axis
    {
        int inSize = 0;
        int outSize = 0;
        std::vector<int> start;
        std::vector<int> count;
        std::vector<float> weights;  // packed, count[i] entries per output
        std::vector<int> offset;
    };

    static void build(Axis& axis, int inSize, int outSize);

    Axis _horizontal;
    Axis _vertical;
    std::vector<float> _scratch;
};

// The model's input: disparity, divergence feature, convergence feature.
// `depth` is already mapped and resized. Writes 3 * width * height floats.
void buildInputTensor(const float* depth, int width, int height,
                      double divergence, double convergence,
                      bool preserveScreenBorder,
                      std::vector<float>& out);

// delta_scale, from the *depth's* width, not the image's.
float deltaScale(int depthWidth);

// Red/cyan Dubois. Each row of the matrix sums to 1.0 across all six
// coefficients, so a grey pair stays grey; that is the property the test checks.
void duboisAnaglyph(const float* left, const float* right, size_t pixels, float* out);

}  // namespace iw3
